{% set versions = {
    "5.9.1": "86b9b046d7f25627ce2aab6847ef1c5534972f4bae18de98225080cf5086919c"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "lhapdf5")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://lhapdf.hepforge.org/downloads/?f=old/lhapdf-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
  patches:
  - patches/fix-octave-tests.patch

requirements:
  build:
    - 'python=2.7'
    - 'numpy=1.16'
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}=8
    - gnuconfig
    - make
    - automake
    - autoconf
    - libtool
    - cmake
  host:
    - 'python=2.7'
    - 'numpy=1.16'
    - libxcrypt
  run:
    - 'python=2.7'
    - 'numpy=1.16'
    - libxcrypt

about:
  home: "https://lhapdf.hepforge.org"
  license: "GPL-3.0"
  summary: "LHAPDF is the standard tool for evaluating parton distribution functions (PDFs) in high-energy physics."
  description: |
    LHAPDF is the standard tool for evaluating parton distribution functions (PDFs) in high-energy physics. PDFs encode the flavour and momentum structure of composite particles, such as protons, pions and nuclei; most cross-section calculations are based on parton-level matrix-elements which must be connected to the real interacting particles, hence PDFs are an essential ingredient of phenomenological and experimental studies at hadron and heavy-ion colliders (e.g. LHC, HERA, Tevatron, EIC, FCC) and in cosmic-ray physics.

extra:
  recipe-maintainers:
    - meiyasan
